types:
    PostalAddress:
        parent: false
        properties:
            addressCountry: { range: "Text" }
            addressLocality: ~
            addressRegion: ~
            postalCode: ~
            streetAddress: ~
    GeoCoordinates:
        parent: false
        properties:
            latitude: { range: "Text" }
            longitude: { range: "Text" }
    Place:
        parent: false
        abstract: true
        properties:
            address: { range: PostalAddress }
            geo: { range: GeoCoordinates }
    House:
        parent: Place
